h=open('index.html',encoding='utf-8').read()
bar=open('mobile_bar.html',encoding='utf-8').read()
css=open('bar.css',encoding='utf-8').read()
js=open('bar.js',encoding='utf-8').read()
print('floats' if '<div class="floats">' in h else 'NO floats')
h=h.replace('</style>',css+'</style>',1)
h=h.replace('<div class="floats">',bar+'<div class="floats">',1)
h=h.replace('</script>\n</body>',js+'</script>\n</body>',1)
open('index.html','w',encoding='utf-8').write(h)
print('barra insertada')
